### ISSUE TITLE
Modal actions disappear on invocation

### ISSUE THREAD

**Issue by michaelwills** [dyadix/codeflections#1]
I like the drill down appearance of the abbreviations. Very nice and quick. In build IU-142.3728.3 (bleeding edge of course) the modals seem to be dismissed immediately when invoked. Is there anything else that may conflict with it?

**Comment by dyadix** [comment]
@michaelwills It would be great if you could give me some more details:
1) What's your OS?
2) What's your JVM version (you can find it in Help|About), eg, JRE...
3) Can you please give also a specific example of a modal which is dismissed.
This will help me to investigate the problem. Thanks!

**Comment by michaelwills** [comment]
1) OS X 10.10.4
2) JRE: 1.8.0_release40-b89 x86_64 JVM: OpenKDK 64-bit Server VM by JetBrains s.r.o.
3) `fa` - the Action window pops up a fraction of a second. `se`, `g*`, etc

`fp`, `ss` work. So those kinds of windows are fine it seems. The small modals seem to have a problem.

**Comment by michaelwills** [comment]
Here is a video demo.

<img src="http://share.michaelangela.name/dropshare/typengo-demo-TWAht3WP6gwz.gif" alt="">

**Comment by michaelwills** [comment]
@dyadix I use the EAP versions and try to keep up to date. At some point with your update and the EAP update it all works as expected. And I use it all the time now. :)

Great plugin and thanks much!
